# Generated by Django 4.2.6 on 2024-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
