# Generated by Django 5.0.2 on 2024-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
