# Generated by Django 5.0.2 on 2024-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_otpmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='otp',
        ),
    ]
